### ISSUE TITLE
Can not work on FFmpeg-4.3.1

### ISSUE THREAD

**Issue by numberwolf** [nervous-systems/ffmpeg-opengl#6]
### Env

System: Centos 7.5
FFmpeg: 4.3.1

### error message

```shell
[AVFilterGraph @ 0x5a46fc0] Error initializing filter 'genericshader'
Segmentation fault (core dumped)
```

Then I get the desc from coredump:

```shell
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000041afcf in uninit (ctx=<optimized out>) at libavfilter/vf_genericshader.c:157
#2  0x00000000004e9793 in avfilter_free (filter=0x4386d40) at libavfilter/avfilter.c:753
#3  0x00000000004fe991 in create_filter (log_ctx=0x4385240, args=0x0, name=0x43853c0 "genericshader", index=70799936, ctx=0x43853c0,
    filt_ctx=0x7ffe24e0f698) at libavfilter/graphparser.c:156
#4  parse_filter (filt_ctx=filt_ctx@entry=0x7ffe24e0f698, buf=buf@entry=0x7ffe24e0f678, graph=graph@entry=0x4385240,
    index=index@entry=0, log_ctx=log_ctx@entry=0x4385240) at libavfilter/graphparser.c:192
#5  0x00000000004ff2e8 in avfilter_graph_parse2 (graph=0x4385240, filters=<optimized out>, filters@entry=0x3b24920 "genericshader",
    inputs=inputs@entry=0x7ffe24e0f738, outputs=outputs@entry=0x7ffe24e0f740) at libavfilter/graphparser.c:427
#6  0x00000000004b07dd in configure_filtergraph (fg=fg@entry=0x3b25300) at fftools/ffmpeg_filter.c:1062
#7  0x00000000004c1cad in ifilter_send_frame (frame=0x3d84900, ifilter=0x3b25480) at fftools/ffmpeg.c:2166
#8  send_frame_to_filters (ist=ist@entry=0x3b22e00, decoded_frame=decoded_frame@entry=0x3d84900) at fftools/ffmpeg.c:2247
#9  0x00000000004c2501 in decode_video (ist=ist@entry=0x3b22e00, pkt=pkt@entry=0x7ffe24e10390,
    got_output=got_output@entry=0x7ffe24e100a0, duration_pts=duration_pts@entry=0x7ffe24e100a8, eof=eof@entry=0,
    decode_failed=decode_failed@entry=0x7ffe24e100a4) at fftools/ffmpeg.c:2446
#10 0x00000000004c4642 in process_input_packet (no_eof=0, pkt=0x7ffe24e10330, ist=0x3b22e00) at fftools/ffmpeg.c:2600
#11 process_input (file_index=<optimized out>) at fftools/ffmpeg.c:4491
#12 0x00000000004c75d3 in transcode_step () at fftools/ffmpeg.c:4611
#13 transcode () at fftools/ffmpeg.c:4665
#14 0x00000000004a28dd in main (argc=<optimized out>, argv=0x7ffe24e10c88) at fftools/ffmpeg.c:4870
(gdb)
```

**Comment by numberwolf** [comment]
I have fix this problem
1）update diff for ffmpeg4
2）add error check
3）windows check
4）xvfb needed
